baseURL = "https://www.psicologoscolastico.it/"
title = "psicologoscolastico"
theme = "psicologoscolastico-theme"
staticDir = ["assets"]
defaultContentLanguage = "it"
google_verification = "123"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
googleAnalytics = "G-VLRQ226NHR"


[languages]
    [languages.it]
    languageName = "IT"
    languageCode = "it"
    title = "psicologoscolastico"
    weight = 1

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2


[outputs]
    home = ["HTML", "JSON"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
    contactFormUrl = "https://getform.io/f/f9dd923a-c85d-4bdb-b1a5-0ed4108f507a"
    recaptchaKey = "6LeAP8EeAAAAACoSrA97pdumqhG8MS1ZGtAiW21W"
    ogImage = "logo.svg"
    ahrefsSiteVerification = "db33085043a2bb7da1d94bef763d8ab5074838837d68250eb12fda61c32588f5"
    enableChat = false
    enableRecaptcha = true
    enableScrollToTopButton = false

[social]
  twitter = "CertQuestions"